const alert = require("./alert.part");
const breadcrumbs = require("./breadcrumbs.part");
const buttonGroup = require("./button_group.part");
const button = require("./button.part");
const calendarRange = require("./calendar_range.part");
const calendar = require("./calendar.part");
const carousel = require("./carousel.part");
const changer = require("./changer.part");
const checkField = require("./check_field.part");
const code = require("./code.part");
const confirm = require("./confirm.part");
const contentChanger = require("./content_changer.part");
const crossList = require("./cross_list.part");
const dropDown = require("./drop_down.part");
const dropField = require("./drop_field.part");
const dropList = require("./drop_list.part");
const dropTag = require("./drop_tag.part");
const fileDrop = require("./file_drop.part");
const fileField = require("./file_field.part");
const filter = require("./filter.part");
const form = require("./form.part");
const headerNotification = require("./header_notification.part");
const highlightBox = require("./highlight_box.part");
const hoveringBox = require("./hovering_box.part");
const imageLazy = require("./image_lazy.part");
const imageUpload = require("./image_upload.part");
const image = require("./image.part");
const incrementalField = require("./incremental_field.part");
const info = require("./info.part");
const lightbox = require("./lightbox.part");
const linkConfirm = require("./link_confirm.part");
const link = require("./link.part");
const list = require("./list.part");
const menuLink = require("./menu_link.part");
const menu = require("./menu.part");
const notification = require("./notification.part");
const option = require("./option.part");
const overlayPanel = require("./overlay_panel.part");
const overlaySearch = require("./overlay_search.part");
const overlay = require("./overlay.part");
const panelMore = require("./panel_more.part");
const panelStack = require("./panel_stack.part");
const panel = require("./panel.part");
const passwordMeter = require("./password_meter.part");
const progressBar = require("./progress_bar.part");
const radioField = require("./radio_field.part");
const rating = require("./rating.part");
const scrollList = require("./scroll_list.part");
const selectField = require("./select_field.part");
const selectList = require("./select_list.part");
const sidePanel = require("./side_panel.part");
const sliderBar = require("./slider_bar.part");
const slider = require("./slider.part");
const slideshow = require("./slideshow.part");
const sourceList = require("./source_list.part");
const stack = require("./stack.part");
const tabPanel = require("./tab_panel.part");
const table = require("./table.part");
const tagField = require("./tag_field.part");
const textField = require("./text_field.part");
const toggleField = require("./toggle_field.part");
const uploader = require("./uploader.part");
const window = require("./window.part");
const wizard = require("./wizard.part");

Object.assign(module.exports, alert);
Object.assign(module.exports, breadcrumbs);
Object.assign(module.exports, buttonGroup);
Object.assign(module.exports, button);
Object.assign(module.exports, calendarRange);
Object.assign(module.exports, calendar);
Object.assign(module.exports, carousel);
Object.assign(module.exports, changer);
Object.assign(module.exports, checkField);
Object.assign(module.exports, code);
Object.assign(module.exports, confirm);
Object.assign(module.exports, contentChanger);
Object.assign(module.exports, crossList);
Object.assign(module.exports, dropDown);
Object.assign(module.exports, dropField);
Object.assign(module.exports, dropList);
Object.assign(module.exports, dropTag);
Object.assign(module.exports, fileDrop);
Object.assign(module.exports, fileField);
Object.assign(module.exports, filter);
Object.assign(module.exports, form);
Object.assign(module.exports, headerNotification);
Object.assign(module.exports, highlightBox);
Object.assign(module.exports, hoveringBox);
Object.assign(module.exports, imageLazy);
Object.assign(module.exports, imageUpload);
Object.assign(module.exports, image);
Object.assign(module.exports, incrementalField);
Object.assign(module.exports, info);
Object.assign(module.exports, lightbox);
Object.assign(module.exports, linkConfirm);
Object.assign(module.exports, link);
Object.assign(module.exports, list);
Object.assign(module.exports, menuLink);
Object.assign(module.exports, menu);
Object.assign(module.exports, notification);
Object.assign(module.exports, option);
Object.assign(module.exports, overlayPanel);
Object.assign(module.exports, overlaySearch);
Object.assign(module.exports, overlay);
Object.assign(module.exports, panelMore);
Object.assign(module.exports, panelStack);
Object.assign(module.exports, panel);
Object.assign(module.exports, passwordMeter);
Object.assign(module.exports, progressBar);
Object.assign(module.exports, radioField);
Object.assign(module.exports, rating);
Object.assign(module.exports, scrollList);
Object.assign(module.exports, selectField);
Object.assign(module.exports, selectList);
Object.assign(module.exports, sidePanel);
Object.assign(module.exports, sliderBar);
Object.assign(module.exports, slider);
Object.assign(module.exports, slideshow);
Object.assign(module.exports, sourceList);
Object.assign(module.exports, stack);
Object.assign(module.exports, tabPanel);
Object.assign(module.exports, table);
Object.assign(module.exports, tagField);
Object.assign(module.exports, textField);
Object.assign(module.exports, toggleField);
Object.assign(module.exports, uploader);
Object.assign(module.exports, window);
Object.assign(module.exports, wizard);
