const clone = require("./clone.part");
const content = require("./content.part");
const country = require("./country.part");
const decimal = require("./decimal.part");
const document = require("./document.part");
const equals = require("./equals.part");
const error = require("./error.part");
const exception = require("./exception.part");
const format = require("./format.part");
const guid = require("./guid.part");
const locale = require("./locale.part");
const location = require("./location.part");
const object = require("./object.part");
const queue = require("./queue.part");
const resolve = require("./resolve.part");
const round = require("./round.part");

Object.assign(module.exports, clone);
Object.assign(module.exports, content);
Object.assign(module.exports, country);
Object.assign(module.exports, decimal);
Object.assign(module.exports, document);
Object.assign(module.exports, equals);
Object.assign(module.exports, error);
Object.assign(module.exports, exception);
Object.assign(module.exports, format);
Object.assign(module.exports, guid);
Object.assign(module.exports, locale);
Object.assign(module.exports, location);
Object.assign(module.exports, object);
Object.assign(module.exports, queue);
Object.assign(module.exports, resolve);
Object.assign(module.exports, round);
