const attr = require("./attr.part");
const browser = require("./browser.part");
const disable = require("./disable.part");
const enable = require("./enable.part");
const feature = require("./feature.part");
const fields = require("./fields.part");
const float = require("./float.part");
const fullscreen = require("./fullscreen.part");
const indom = require("./indom.part");
const int = require("./int.part");
const mobile = require("./mobile.part");
const original = require("./original.part");
const print = require("./print.part");
const reset = require("./reset.part");
const resize = require("./resize.part");
const responsive = require("./responsive.part");
const value = require("./value.part");

Object.assign(module.exports, attr);
Object.assign(module.exports, browser);
Object.assign(module.exports, disable);
Object.assign(module.exports, enable);
Object.assign(module.exports, feature);
Object.assign(module.exports, fields);
Object.assign(module.exports, float);
Object.assign(module.exports, fullscreen);
Object.assign(module.exports, indom);
Object.assign(module.exports, int);
Object.assign(module.exports, mobile);
Object.assign(module.exports, original);
Object.assign(module.exports, print);
Object.assign(module.exports, reset);
Object.assign(module.exports, resize);
Object.assign(module.exports, responsive);
Object.assign(module.exports, value);
